#!/usr/bin/env bash


try_assume_role(){    
  # temporary file where to store credentials
  TEMP_STS_ASSUMED_FILE=$(mktemp -t prowler.sts_assumed-XXXXXX)
  # assume role command
  if [[ -z $EXTERNAL_ID ]]; then
    $AWSCLI sts assume-role --role-arn $ROLE \
      --role-session-name ProwlerAssessmentSession \
      --duration-seconds 3600 > $TEMP_STS_ASSUMED_FILE
  
  res=$?
  else
   $AWSCLI sts assume-role --role-arn $ROLE \
      --role-session-name ProwlerAssessmentSession \
      --duration-seconds 3600 \
	  --external-id $EXTERNAL_ID> $TEMP_STS_ASSUMED_FILE
  res=$?
  fi

  # a non-zero res means a failed execution
  if [ "$res" -ne "0" ]; then 
    return $res
  fi

  # set env variables with assumed role credentials
  export AWS_ACCESS_KEY_ID=$(cat $TEMP_STS_ASSUMED_FILE | jq -r '.Credentials.AccessKeyId')
  export AWS_SECRET_ACCESS_KEY=$(cat $TEMP_STS_ASSUMED_FILE | jq -r '.Credentials.SecretAccessKey')
  export AWS_SESSION_TOKEN=$(cat $TEMP_STS_ASSUMED_FILE | jq -r '.Credentials.SessionToken')
  export EXPIRYTIME=$(cat $TEMP_STS_ASSUMED_FILE | jq -r '.Credentials.Expiration')
  rm -fr $TEMP_STS_ASSUMED_FILE
}